services:
  air_quality_dashboard:
    network_mode: host # Bugfix for Windows when using Docker Desktop, 
                       #remove this line if you are using Linux  
    container_name: air_quality_dashboard
    image: alandolt/air_quality_dashboard
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8081:8081"
    command: "python /air_quality_dashboard/main.py"